[tasks.run]
command = "cargo"
args = ["run", "--", "-i", "input.txt", "-d", "${@}"]

[tasks.dev]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-q", "-c", "-w", "src/", "-x", "test"]
