[tasks.run]
command = "cargo"
args = ["run", "--", "-i", "input.txt", "-d", "${@}"]

[tasks.dev]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-B=0","-q", "-c", "-w", "src/", "-x", "nextest run ${@}"]

[tasks.test]
install_crate = "cargo-nextest"
command = "cargo"
args = ["nextest", "run", "${@}"]
