[tasks.run]
command = "cargo"
args = ["run", "--", "-i", "input.txt", "-d", "${@}"]

[tasks.dev]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-q", "-c", "-w", "src/", "-x", "test"]

[tasks.test]
install_crate = "cargo-nextest"
command = "cargo"
args = ["nextest", "run", "${@}"]

[config]
reduce_output = true
